//
// EPITECH PROJECT, 2018
// zappy
// File description:
// EID.hpp
//

#ifndef EID_HPP
#define EID_HPP

enum ID {
	NONE = 100, LISTBOX, TABLE, MENU_HEADER, MENU_TITLE, MENU_PANEL,
	MENU_BTN_EXIT, MENU_BTN_CANCEL_MENU, MENU_BTN_CANCEL_CREDITS,
	MENU_BTN_CANCEL_OPTIONS, MENU_BTN_OPTIONS, MENU_BTN_CREDITS,
	MENU_MENU_TEXT, MENU_OPTIONS_TEXT, MENU_CREDITS_TEXT,	
	OPEN_MENU, MENU_SRV_PANEL, SRV_FIRST_OK, SRV_SECOND_OK,
	LAUNCH_GAME, ADD_TEAM1, ADD_TEAM2, ADD_TEAM3, ADD_TEAM4, NEXT_SONG,
	INVENTORY_PANEL, INV_VALUE_1, INV_VALUE_2, INV_VALUE_3, INV_VALUE_4,
	INV_VALUE_5, INV_VALUE_6, INV_VALUE_7, INV_IMG_1, INV_IMG_2, INV_IMG_3,
	INV_IMG_4, INV_IMG_5, INV_IMG_6, INV_IMG_7, TIMER_PANEL, TIMER_TEXT_1,
	TIMER_TEXT_2, CHANGE_SKYBOX
};

#endif

