//
// EPITECH PROJECT, 2018
// zappy
// File description:
// EID.hpp
//

#ifndef EID_HPP
#define EID_HPP

enum ID {
	NONE = 100, LISTBOX, TABLE, MENU_HEADER, MENU_TITLE, MENU_PANEL,
	MENU_BTN_EXIT, MENU_BTN_CANCEL_MENU, MENU_BTN_CANCEL_CREDITS,
	MENU_BTN_CANCEL_OPTIONS, MENU_BTN_OPTIONS, MENU_BTN_CREDITS,
	MENU_MENU_TEXT, MENU_OPTIONS_TEXT, MENU_CREDITS_TEXT,	
	OPEN_MENU, MENU_SRV_PANEL, SRV_FIRST_OK, SRV_SECOND_OK,
	LAUNCH_GAME, ADD_TEAM1, ADD_TEAM2, ADD_TEAM3, ADD_TEAM4, NEXT_SONG,
	CHANGE_SKYBOX
};

#endif
